function converter()

col_var1 = 0.300    %color variable to main window
col_var2 = 0.900    %color variable to popup   
col_var4 = 0.750    %color variable to value fields

width = 400
height = 300

t_posY = 200

%THINGS TO DO
%ADD NICE TITLE ON THE DARKGREY BACKGROUND
%ADD LEGEND TO THE BUTTON CALCULATE AND 

% MAIN WINDOW
    window = figure('Color', [col_var1 col_var1 col_var1],...    % window bcg color
                'Name', 'Energy Units Converter',...    % window title
                'DockControl', 'off',...                % window docking
                'Units', 'Pixels',...                   % units setting  
                'Position', [60 100 width height]);    % posX posY sizeX sizeY             
% POP-UPS            
    first_popup = uicontrol('Parent', window,...
                        'Style', 'popup',..., 
                        'BackgroundColor', [col_var2 col_var2 col_var2],...
                        'String', {'Joule', 'Electronovolt','Calorie','Kilowatt Hour','Kilocalorie'},...
                        'Units', 'pixels',...
                        'Position', [25,150,100,100]);         
    second_popup = uicontrol('Parent', window,...
                        'Style', 'popup',..., 
                        'BackgroundColor', [col_var2 col_var2 col_var2],...
                        'String', {'Joule', 'Electronovolt','Calorie','Kilowatt Hour','Kilocalorie'},...
                        'Units', 'pixels',...
                        'Position', [width-125,150,100,100]);
% ENTERED VALUE 
     value_1 = uicontrol('Parent', window,...
                   'Style', 'edit',...,
                    'String', '0.0',...
                    'FontSize', 10,...
                    'ForegroundColor',[0 0 0],...
                    'BackgroundColor', [col_var4 col_var4 col_var4],...
                    'Units', 'pixels',...
                    'Position', [25,t_posY-20,150,40]); 
% RESULT
     value_2 = uicontrol('Parent', window,...
                    'Style', 'text',...,
                    'String', 'Result',...
                    'ForegroundColor',[0 0 0],...
                    'BackgroundColor', [col_var4 col_var4 col_var4],...
                    'FontSize', 10,...
                    'FontWeight', 'bold',...
                    'Units', 'pixels',...
                    'Position', [width-175,t_posY-20,150,40]);
% CHAR '='
     char = uicontrol('Parent', window,...
                    'BackgroundColor', [col_var1 col_var1 col_var1],...
                    'Style', 'text',...,
                    'String', '=',...
                    'Units', 'pixels',...
                    'FontSize', 25,...
                    'ForegroundColor',[1 1 1],...
                    'Position', [191,t_posY-17,20,40]);
% TITLE
     title = uicontrol('Parent', window,...
                    'BackgroundColor', [col_var1 col_var1 col_var1],...
                    'Style', 'text',...,
                    'String', 'Energy Units Converter',...
                    'Units', 'pixels',...
                    'FontSize', 16,...
                    'ForegroundColor',[1 1 1],...
                    'Position', [75,250,250,40]);
% CALCULATING BUTTON  %MAYBE 'ENTER' TO CALCULATING
    btn = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...,
                    'String', 'calculate',...
                    'BackgroundColor', [1 1 1],...
                    'ForegroundColor', [1 0 1],...
                    'Units', 'pixels',...
                    'Position', [150,230,100,20],...
                    'Callback', @calculate); 
% BUTTON  TO GETTING DATA AND SAVING TO THE TEXT FILE        
btn = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...,
                    'String', 'calculate data from EXCEL',...
                    'BackgroundColor', [1 1 1],...
                    'ForegroundColor', [0.5 0 1],...
                    'Units', 'pixels',...
                    'Position', [25,75,150,40],...
                    'Callback', @load_calc); 
% BUTTON  TO GETTING DATA FROM TXT AND SAVING TO THE TEXT FILE        
btn = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...,
                    'String', 'calculate data from TXT',...
                    'BackgroundColor', [1 1 1],...
                    'ForegroundColor', [0.5 0 1],...
                    'Units', 'pixels',...
                    'Position', [225,75,150,40],...
                    'Callback', @load_calc2); 
% text that all gone great
     stri = uicontrol('Parent', window,...
                    'BackgroundColor', [col_var1 col_var1 col_var1],...
                    'Style', 'text',...,
                    'String', ' ',...
                    'Units', 'pixels',...
                    'FontSize', 10,...
                    'ForegroundColor',[1 1 1],...
                    'Position', [100,10,200,40]);
% GATHERING DATA AND CALCULATING
    function calculate(var1,var2)
        str = get(value_1, 'String'); %gets the strings from field
        value = str2double(str);              %converts to the double variable
        p1 = get(first_popup, 'Value'); %gets the value from the first popup
        p2 = get(second_popup, 'Value');   %gets the value from the second popup
        
        x=conversion_factor(p1,p2);         %using a function 
        result=x*value;                     %calculation
        set(value_2, 'String', result);     %print the result
    end

    function [x] = conversion_factor(p1,p2) %function chooses the acurate conv. factor
        j_ev = 6241509744512000000   % J -> eV
        ev_j = 1/j_ev                % Ev -> J
        j_cal = 0.2388458966275      % J -> cal
        cal_j = 1/j_cal              % cal -> J
        kwh_j = 3600000              % Kwh -> J
        j_kwh = 1/kwh_j              % J -> Kwh
        j_kcal = 0.0002388458966275  % J -> Kcal
        kcal_j = 1/j_kcal            % Kcal -> J
        
        if(p1==1 && p2==2)      x = j_ev;
        elseif(p1==1 && p2==3)  x = j_cal;
        elseif(p1==1 && p2==4 ) x = j_kwh;
        elseif(p1==1 && p2==5 ) x = j_kcal ;
        elseif(p1==2 && p2==1 ) x = ev_j ;
        elseif(p1==2 && p2==3 ) x = ev_j*j_cal ;
        elseif(p1==2 && p2==4 ) x = ev_j*j_kwh ;
        elseif(p1==2 && p2==5 ) x = ev_j*j_kcal;
        elseif(p1==3 && p2==1 ) x = cal_j ;
        elseif(p1==3 && p2==2 ) x = cal_j*j_ev ;
        elseif(p1==3 && p2==4 ) x = cal_j*j_kwh ;
        elseif(p1==3 && p2==5 ) x = cal_j*j_kcal ;
        elseif(p1==4 && p2==1 ) x = kwh_j ;
        elseif(p1==4 && p2==2 ) x = kwh_j*j_ev ;
        elseif(p1==4 && p2==3 ) x = kwh_j*j_cal ;
        elseif(p1==4 && p2==5 ) x = kwh_j*j_kcal ;
        elseif(p1==5 && p2==1 ) x = kcal_j ;
        elseif(p1==5 && p2==2 ) x = kcal_j*j_ev ;
        elseif(p1==5 && p2==3 ) x = kcal_j*j_cal ;
        elseif(p1==5 && p2==4 ) x = kcal_j*j_kwh ;
        else
            x=1;       %when the units are the same
        end %end of if
    end % end of function 
    
    function load_calc(p1,p2,x)
      p1 = get(first_popup, 'Value'); %gets the value from the first popup
      p2 = get(second_popup, 'Value');   %gets the value from the second popup
      x = conversion_factor(p1,p2);       % function call
      A = xlsread('data.xlsx','A2:Z2')
      A=A.*x;                           % counting
      fid = fopen('results_excel.txt','w');   % openin txt file where should save results
      save 'results_excel.txt' A -ascii       % saving matrix to the results
      status = fclose(fid);             % closing
      set(stri, 'String', 'Data Converted');     %print the result
    end

    function load_calc2(p1,p2,x)
      p1 = get(first_popup, 'Value'); %gets the value from the first popup
      p2 = get(second_popup, 'Value');   %gets the value from the second popup
      x = conversion_factor(p1,p2);       % function call
      t = load('data.txt');           % loading txt file
      A=dlmread('data.txt');          % creating Matrix with values
      A=A.*x;                           % counting
      fid = fopen('results_txt.txt','w');   % openin txt file where should save results
      save 'results_txt.txt' A -ascii       % saving matrix to the results
      status = fclose(fid); % closing
      set(stri,'String', 'Data Converted');
    end

end % end of main function